FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" -o /bin/processor ./cmd/processor

FROM gcr.io/distroless/static-debian12
COPY --from=builder /bin/processor /processor
USER nonroot:nonroot
ENTRYPOINT ["/processor"]
